### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-css-sass-intro-8dVLYn#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-css-sass-intro-8dVLYn/) and meets the following criteria:

- [x] All components in [this HTML](https://gist.github.com/egillespie/15433761e640077f93660b4555a3d88b) are styled using Sass
- [x] Use four colors from a [random color palette](https://coolors.co/) (just copy the hex values into your Sass file) and link to your palette in the HTML
- [x] Font sizes are all determined by one base font size variable, even in `input` and `textarea` elements
- [x] All text uses the same font family, even in `input` and `textarea` elements
- [x] Elements shaped like a box (`img`, `input[type="text"]`, `textarea`) have the same `border-radius`
- [x] At least one built-in Sass function is used to style a component
- [x] Variables are defined in their own Sass file
- [x] Sass files are saved in a `source` directory and CSS files are saved in a `compiled` directory
- [x] A source map for your component library is included in the project

**Comment by stuartpearman** [comment]
Hey Kyle, the font-sizes are good, nice work with that. The rest of the project seemed very bare minimum, which I understand, I'd like to see at the very least the basic criteria met.

This criteria needs to be revisited:

> All components in this HTML are styled using Sass

And:

> Use four colors from a random color palette (just copy the hex values into your Sass file) and link to your palette in the HTML

If you have any questions, just let me know, happy to help! :+1:

**Comment by harr1193** [comment]
Improved the layout of the page from looking at some examples, and all the items are styled with sass

**Comment by stuartpearman** [comment]
This is awesome Kyle! This is some professional quality work. Nice job! :shipit:
